### ISSUE TITLE
PyPI package

### ISSUE THREAD

**Issue by arve0** [tomduck/pandoc-fignos#1]
Hi!
Great package :+1: Why not release it to pypi?

**Comment by tomduck** [comment]
Hey, thanks.  And yes, this is a very good idea.

**Comment by tomduck** [comment]
Done.  You can now install using

```
$ sudo pip install pandoc-fignos
```

Please let me know if you have any difficulties with it.

**Comment by tomduck** [comment]
@arve0: Could you test the installation with `pip` for me?  If it works for you then I will close this issue.  Thanks!

**Comment by arve0** [comment]
Hi! I've been finishing my master thesis, so sorry for the delay.

Seems like you rely on [ez_setup](https://pypi.python.org/pypi/ez_setup), which is not installed as default. Why no use setuptools?

**Comment by tomduck** [comment]
Thanks, @arve0.  I followed the [instructions for distributing a setuptools-based-project](https://pythonhosted.org/setuptools/setuptools.html#distributing-a-setuptools-based-project) in my use of ez_setup.py, which automatically installs setuptools if it is missing.  Note that setuptools is used in setup.py for [automatic script creation](https://pythonhosted.org/setuptools/setuptools.html#automatic-script-creation).

**Comment by arve0** [comment]
Hm, ok. I think `ez_setup` is outdated, last release was in 2010. `setuptools` is recommended by [Python Packaging Authority](https://packaging.python.org/en/latest/), and is installed on most systems.

For cutting some corners I might recommend [cookiecutter](https://github.com/audreyr/cookiecutter) for scaffolding new projects with sane defaults (packaging, testing, etc). [Here's](https://github.com/arve0/cookiecutter-pypackage) mine. `cookiecutter gh:arve0/cookiecutter-pypackage` will then scaffold the project.

**Comment by tomduck** [comment]
I'm not sure that I understand. The `pandoc-fignos` installer does use `setuptools`.  The `setuptools` documentation [recommends](https://pythonhosted.org/setuptools/setuptools.html#distributing-a-setuptools-based-project) using `ez_setup.py` to ensure that `setuptools` is installed.  If I could count on `setuptools` being installed, then there would be no need for `ez_setup.py`.

I haven't come across cookiecutter before, but will check it out.  Cheers. :o)

**Comment by arve0** [comment]
Yes, but you need to package ez_setup along also. Right now, it's not included in the tarball. You might want to install [setuptools-git](https://pypi.python.org/pypi/setuptools-git) in your build env.

**Comment by tomduck** [comment]
Whoops!  Good catch.  I'm on it.  :o)

**Comment by tomduck** [comment]
@arve0: I now have `ez_setup.py` included in the `MANIFEST.in` on github.  If it looks good to you, then I will push out a new version to pypi.

**Comment by arve0** [comment]
Looks fine to me :+1:

**Comment by tomduck** [comment]
Excellent.  0.2.1 is now uploaded to pypi.

Thanks again for your help, @arve0.  If you have any further issues with it, please do let me know.
