### ISSUE TITLE
Just stopped working

### ISSUE THREAD

**Issue by retrography** [tomduck/pandoc-fignos#10]
After updating my Python environment, the plugin simply stopped working (does not replace the tags at all). No error or warning is issued. Tablenos still seems to work properly.

Info:

Python 2.7.11
pandoc 1.16.0.2
pandocfilters 1.3.0
pandoc-attributes 0.1.7
pandoc-fignos 0.7.6

**Comment by retrography** [comment]
My mistake. Found the issue. 

I had a space between the filename and the tag, and this doesn't seem to be allowed anymore:

```
![desc](filename) {#fig:tag}
```

**Comment by tomduck** [comment]
No worries.  The change was made because spaces are not allowed by pandoc’s newly-introduced figure attributes.  The original attributes spec from pandoc Issue #813 did allow them.
