### ISSUE TITLE
Feature Request: Customizable "Figure" label

### ISSUE THREAD

**Issue by onevcat** [tomduck/pandoc-fignos#12]
Hi,

Currently fignos transform the `![Some data.](img/plot1.png){#fig:data}` to something like `Figure 2.1`.

However, we are now working on a Chinese version of our book, in which we prefer a localized label for word "Figure". e.g, in Chinese, it should be "图 2.1".

I had a look at related code, and it seems this is hard coded. But I am not a Pythoner at all so there might be a chance I missed something.

Is there a way now to specify the figure label to other text instead of "Figure"?

Thanks!

**Comment by tomduck** [comment]
Thanks for your feedback.  This isn't yet part of pandoc-fignos, but it shouldn't be hard to do.  Let me get back to you.

**Comment by onevcat** [comment]
Awesome! Looking forward your news on it.

Thank you.

**Comment by tomduck** [comment]
Done!  I have posted a new version to the `figure-name` branch.  @onevcat , would you mind testing it out?  You will need to install from the `figure-name` source (not `pip`).

To change the figure name, you may set the `figure-name` variable in either your document's metadata block OR via a command-line argument.  This works seamlessly for _all_ output formats.

**e.g. 1: metadata block**

Consider the following `example.md`:

```
---
figure-name: Fig.
...
This is a test.
```

Process this with 

```
pandoc example.md -o example.pdf --filter pandoc-fignos
```

**e.g. 2: command line alone**

Consider the following `example.md`:

```
This is a test.
```

Process this with

```
pandoc example.md -o example.pdf --filter pandoc-fignos -M figure-name=Fig.
```

---

**EDIT:** I renamed everything from figure-title to figure-name so as to be more consistent with latex's naming.

**Comment by onevcat** [comment]
Oh, @tomduck 

Thanks for it! But it is too late for me now. I will try it tomorrow!

**Comment by tomduck** [comment]
Sounds good, @onevcat.  Talk to you then. :o)

**Comment by tomduck** [comment]
Note: I changed everything from `figure-title` to `figure-name` to be more consistent with latex's naming.  I updated the comment above as well.

**Comment by onevcat** [comment]
Hi, @tomduck 

It works like a charm!

**Comment by tomduck** [comment]
_Excellent_.  I merged this to `master` and tagged it as version `0.10`.  The new version has been pushed out to pypi so that people can install it with `pip`.

Thanks again for your feedback. :o)

**Comment by onevcat** [comment]
Amazing! Thanks for this.

Have a good weekend!

**Comment by tomduck** [comment]
Hi @onevcat.  I just wanted to mention that I have changed the metadata field name to `fignos-caption-name`.  `figure-name` still works, and will continue to work, but is now deprecated.  The change was made because I have added new options (and also to pandoc-eqnos/tablenos) and am trying to keep the naming consistent.  Cheers.

**Comment by onevcat** [comment]
@tomduck Thanks a lot for mentioning it! I will upgrade to latest version and adopt to the new parameter name!

Thank you for your work on that!
