### ISSUE TITLE
completely broken output

### ISSUE THREAD

**Issue by ddavidebor** [tomduck/pandoc-fignos#16]
Dear Tom,

After an update the output is broken on both mac and ubuntu.

``` bash
air-di-davide:~ davide$ pip show pandoc-fignos

---
Metadata-Version: 2.0
Name: pandoc-fignos
Version: 0.12
Summary: Figure number filter for pandoc
Home-page: https://github.com/tomduck/pandoc-fignos
Author: Thomas J. Duck
Author-email: tomduck@tomduck.ca
Installer: pip
License: GPL
Location: /usr/local/lib/python2.7/site-packages
Requires: psutil, pandocfilters, pandoc-attributes
Classifiers:
  Development Status :: 4 - Beta
  Intended Audience :: End Users/Desktop
  Environment :: Console
  License :: OSI Approved :: GNU General Public License v3 (GPLv3)
  Programming Language :: Python
Entry-points:
  [console_scripts]
  pandoc-fignos = pandoc_fignos:main
air-di-davide:~ davide$ 
```

attached a few exports

[Hall_Handbook.docx](https://github.com/tomduck/pandoc-fignos/files/241027/Hall_Handbook.docx)

[Hall_Handbook.pdf](https://github.com/tomduck/pandoc-fignos/files/241026/Hall_Handbook.pdf)

**Comment by tomduck** [comment]
Thanks for getting in touch about this, @ddavidebor.  I haven't been able to reproduce your errors yet, so there must be something we are doing differently.  It would be good to track down what that is.

As a start, could you try building the [demos](https://github.com/tomduck/pandoc-fignos/tree/master/demos) that I provide on GitHub?

It would also be helpful to know what version of pandoc you are using.  I can see that you are using python2.7.

**Comment by tomduck** [comment]
I just posted a new version to pypi.  Maybe it will solve the problem.

**Comment by ddavidebor** [comment]
I'm sorry for the missed reply. 

I've built your demo, they seems to work perfectly. results attached.

I have still problems on osx, will post soon.
[out.zip](https://github.com/tomduck/pandoc-fignos/files/268877/out.zip)

**Comment by tomduck** [comment]
Thanks, @ddavidebor.  My development computer is a Mac, so it will be interesting to see what we are doing differently.

Please feel welcome to post links to your results, or copy them directly here.

**Comment by ddavidebor** [comment]
i'm trying to test across platforms but i'm stuck with this problem on the ubuntu-based CI.

You can see the full log here:
https://travis-ci.org/fermiumlabs/Hall-effect-apparatus/builds/130979663

**Comment by ddavidebor** [comment]
Other deployment results https://travis-ci.org/fermiumlabs/Hall-effect-apparatus/builds/140125422

**Comment by ddavidebor** [comment]
seems solved upgrading everything
