### ISSUE TITLE
Referencing one figure from another's caption results in an error

### ISSUE THREAD

**Issue by marc-jones** [tomduck/pandoc-fignos#17]
Something like:

```
![Figure 1](figures/figure_1.pdf){#fig:figure_one}
![Figure 2 - Subset of Figure @fig:figure_one](figures/figure_2.pdf){#fig:figure_two}
```

Leads to an error:

```
pandoc-citeproc: reference with no printed form
```

Weirdly, removing `--filter pandoc-citeproc` from my call to `pandoc` still results in the above error.

**Comment by tomduck** [comment]
Hi @marc-jones!  I'm wondering if you are using the latest version, pandoc-fignos 0.14?  This is an issue that I very recently fixed.  I tested your example, and it works for both pdf and html output.  Note, however, that you need a blank line between the two figures.

**Comment by marc-jones** [comment]
Thank you, updating solved the problem. Many thanks for your reply and for a really useful filter!

**Comment by tomduck** [comment]
Excellent.  Thanks for the feedback!  Cheers. :o)
