### ISSUE TITLE
Inter-figure references in captions

### ISSUE THREAD

**Issue by derekmerck** [tomduck/pandoc-fignos#18]
Hi @tomduck -- thanks so much for contributing these filters to the community; I use your *nos filters for academic writing all the time!

It currently appears to be impossible to use an `{@fig:my_fig}` reference inside the caption of a tracked figure to reference another one (or itself?).  I can imagine why this kind of recursion would be a pain to support, but I am surprisingly often missing this functionality.  How hard would it be to implement?

**Comment by tomduck** [comment]
Hi, @derekmerck.  Thanks for your feedback, which I appreciate.  I think that you will already find this functionality in the most recent release.  I did a major refactor of the code and fixed a few trouble spots like this one.

Please feel welcome to send along more ideas as they come up.

**Comment by derekmerck** [comment]
I was just responding to you that I was sure that I had the most recent version and it actually wasn't working and fabricating a test case ... and then I forced pip to upgrade and of course now it works.  Thanks for proactively addressing my issue and pointing me to the answer!

Edit:  Also, I finally read the manual and discovered clever referencing.  What a great idea!
