### ISSUE TITLE
clever references with asterisk broken when utilizing asterisk for emphasis

### ISSUE THREAD

**Issue by mckennapsean** [tomduck/pandoc-fignos#19]
As a note, the output is not getting parsed for me in the filter correctly when I have a paragraph using a clever reference with the asterisk if that same paragraph later contains an asterisk for emphasis like `*emphasis*`. The temporary solution/fix is to change the emphasis to use underscores: `_emphasis_`. It also fails if you try to use this referencing more than once in a single paragraph (of which the only solution is to form a new paragraph... not ideal).

Thanks for the awesome filter!

**Comment by tomduck** [comment]
Thanks for the feedback and sorry for the delay.  I can confirm that I see the same effect you are reporting.  The solution -- according to the pandoc docs -- is to backslash escape the star (i.e., `\*`) when you don't want it to be interpreted as an emphasis.

I'm not sure what other approach would be better, but am open to suggestions.  Another possibility would be to use a different character, but that will probably give rise to other problems.  I had hoped that protecting the reference with curly braces would work, but it did not.  Pandoc intercepts the `*` anyway, even when it is mid-word.

In any case, I will add a note to the documentation for the next release, which I hope to push out soon.

**Comment by mckennapsean** [comment]
Cool, thanks for the response!

So, if a paragraph has emphases with asterisks and/or if there are multiple clever references in a single paragraph, it sounds like the fix to the clever reference is as follows: `{\*@fig:id}`

**Comment by tomduck** [comment]
You shouldn't need the brackets.  Simply writing `\*@fig:id` in cases where a sentence contains _emphasis_ should do.

**Comment by tomduck** [comment]
I updated the documentation in the newest release.  Thanks again for the feedback, and please let me know if you have any further trouble with it. Cheers!
