### ISSUE TITLE
docx clickable references

### ISSUE THREAD

**Issue by krnlyng** [tomduck/pandoc-fignos#25]
hi

would it be difficult to implement clickable references in the docx format?
i assume this is not implemented or is it a bug (not clickable references)?

thanks!

**Comment by tomduck** [comment]
Hi @krnlyng.  Thanks for the feedback and sorry for the delay.  I will look into this.

**Comment by krnlyng** [comment]
@tomduck do you think this will be difficult to implement? unfortunately i don't know much about the internals of the docx format, i only know as much as i learned from python-docx, but if i can help let me know.

**Comment by tomduck** [comment]
I wouldn't think this should be difficult.  Let me look into it and get back to you.

**Comment by tomduck** [comment]
@krnlyng: Do pandoc-generated internal links work for you with docx?  I'm having a little trouble with it and suspect that internal links may not be supported by pandoc for docx.

**Comment by krnlyng** [comment]
@tomdoc can you paste a pandoc example which i can try? i remember i had issues with that too but it could be an issue on my side. but references to headings work definately

**Comment by krnlyng** [comment]
i just tested, the following works for me:

> See the [Introduction].
> 
> [Introduction]: #introduction
> hello

at least it creates a link, i am not sure if it is 100% working since i don't have word installed on this machine and libreoffice doesn't seem to follow the link, i will test tomorrow with word.

thanks again!

**Comment by krnlyng** [comment]
i can confirm that they work as mentioned above

**Comment by tomduck** [comment]
Thanks, @krnlyng.  I just pushed out a new release.  Can you give it a try?  If it doesn't work then we will look into this issue a little deeper and see if there is a way to get the fignos docx links to work.

**Comment by krnlyng** [comment]
almost. the references are links but they all go to the first heading

**Comment by krnlyng** [comment]
@tomduck is there anything i can do to help with this feature, can you point me to the involved sources? i have looked at your recent commits but i am not sure if i understand whats going on :)

**Comment by krnlyng** [comment]
ah it is in pandoc-xnos, nvm.

i think i know what is going on.
pandoc seems not to use "proper" word links but only textreferences (sorry if this is the wrong translation).
which means any link to for example
`[foo](#foo)`
will always go to the first occurance of "foo" within the document
sorry for having caused confusion, when i did the test i really thought it was working as it should.

do you think it can still be implemented somehow? i will check if pandoc 1.18 does support this better (if compatible)

EDIT: it does not do it better, and it's not compatible ootb either.

**Comment by tomduck** [comment]
Hi @krnlyng.  Sorry for the delay.  It has been a very busy term.  Finally we are on Fall Break.

You are quite right in your assessment: It appears the problem is in the pandoc docx writer.

I just pushed out new version of pandoc-fignos et al that are compatible with the new pandoc 1.18.  Could you please give it a test and let me know if the issue is resolved?  You would want to install pandoc 1.18 first.

If the bug remains, then I can help put together an Issue report for the pandoc docx writer.  The best approach, I think, will be to put together some JSON that works for html & pdf, but exposes the problem for docx.  It shouldn't be too hard to do.  We know that the docx writer supports internal links for headings, so it can be done (with a bug fix) for internal links as well.

Cheers,
Tom

**Comment by tomduck** [comment]
Hi @krnlyng.  Have you had a change to test out the new pandoc/pandoc-fignos yet?  I'm curious to know if it solves the problem.  Cheers.

**Comment by krnlyng** [comment]
hi @tomduck, i just tested it and it behaves the same way (link goes to the first heading)

**Comment by tomduck** [comment]
OK, thanks.  I will assemble the bits needed for a pandoc Issue report and post them here.  I'm hearing from a few different directions that there are issues with the docx writer.  Cheers.

**Comment by krnlyng** [comment]
@tomduck thank you very much!

**Comment by tomduck** [comment]
@krnlyng: Good news!  I think that I actually have this working.  It is a simple solution that I should have thought of before.

Can you please test the `nextrelease` branch of pandoc-fignos?  The standard way to install it is by executing the following command as root:

~~~
pip install --upgrade git+https://github.com/tomduck/pandoc-fignos.git@nextrelease
~~~

You can also just download the `nextrelease` branch and install it manually.

If it works for you then I will push out a new release, and also port the solution to pandoc-eqnos and pandoc-tablenos.

**Comment by krnlyng** [comment]
it feels like it is not the way how references work in docx for figures as intended but it works great for my purposes thank you very very much!

**Comment by tomduck** [comment]
Thanks, @krnlyng.  Is it the links that don't work as expected, or is it that the figure numbers and references aren't using docx's native capabilities?  I'm now thinking it is possible to use the native capabilities (similar to what I do for LaTeX), although this will take some time to implement.  I need to better understand the docx format first.

Docx is not a format I use, so I have really appreciated all of your feedback and patience. :o)

**Comment by krnlyng** [comment]
they work almost as expected, for me it seems the cursor (when the link is clicked) goes to one line above the image, and the images seem to have one extra newline in front of them. i will check whether this is really true later today. but it works well enough for my purposes. however if you implement it using native features i will happily test it for you. and if there is anything i can do to help i will try my best, but my knowledge about the docx format is limited to what i know from python-docx and from looking at the unzipped output.

i preffer saner formats too but it is unfortunately what i have to use for now, and i really didn't want to fiddle with word too much thats why pandoc and pandoc-fignos are so great to me

**Comment by tomduck** [comment]
I will gratefully accept the help with testing!  I'm seeing increasing interest from different directions in having better docx support.  Thanks again.  Cheers, Tom.

**Comment by tomduck** [comment]
I pushed out a new release with this change.  I also opened up Issue #34 ("Docx native capabilities should be used for figure and reference numbers") to address your other concerns with the docx output.

Thanks again for your feedback, @krnlyng. Cheers, Tom.
