### ISSUE TITLE
Install problem on Windows with Python 2.7.12

### ISSUE THREAD

**Issue by Wind4Greg** [tomduck/pandoc-fignos#26]
Hi Tom, long time user of Fignos and Eqnos.  I was trying to upgrade on Windows with Python 2.7.12 and failed. The error message included: 

```
 File "setup.py", line 46, in run
    super(custom_install, self).run()
TypeError: super() argument 1 must be type, not classobj
```

I then hacked the `setup.py` file as follows (only portions with change showed):

``` python
class custom_install(install, object): # Added object
    """Ensures setuptools uses custom install_scripts."""
    def run(self):
        super(custom_install, self).run() # Added arguments to super

# Custom install_scripts command class for setup()
class install_scripts_quoted_shebang(install_scripts, object):  # added object
    """Ensure there are quotes around shebang paths with spaces."""
    def write_script(self, script_name, contents, mode="t", *ignored):
        shebang = str(contents.splitlines()[0])
        if shebang.startswith('#!') and ' ' in shebang[2:].strip() \
          and '"' not in shebang:
            quoted_shebang = '#!"%s"' % shebang[2:].strip()
            contents = contents.replace(shebang, quoted_shebang)
        super(install_scripts_quoted_shebang, self).write_script(script_name, contents, mode, *ignored)
       # Added arguments to super above
```

After that I was able to complete the install with `python setup.py install`. Saw this problem with eqnos too.  Don't know if this just my environment or a general issues.  

Thanks
Greg B.

**Comment by tomduck** [comment]
Hi Greg,

This is a really good catch -- thanks for the contribution.  I'm going to test this against python3 on Windows and get back to you.

Cheers,
Tom

**Comment by tomduck** [comment]
One question: Is `object` in the two class definitions necessary?  It is not clear to me why it should be so.

**Comment by Wind4Greg** [comment]
Hi Tom, just tried it without `object` and it fails.  I think `from setuptools.command.install import install` uses old style classes (in Python 2.X) hence the need for `object` get to new style classes and the `super` call.  This might not occur with Python3 since they don't have the old style classes.

Cheers
Greg

**Comment by tomduck** [comment]
Thanks for the explanation, Greg.  I have implemented your recommended changes in the `nextrelease` branch.  I will test it against my Win/python3 machine and then make an official release, hopefully within the next few days.

Cheers,
Tom

**Comment by tomduck** [comment]
I have (finally!) pushed the next release out.  Thanks again for your help.  Cheers!
