### ISSUE TITLE
Caption location

### ISSUE THREAD

**Issue by lillemets** [tomduck/pandoc-fignos#29]
I prefer to see captions as titles and descriptions of figures and as such it makes sense to place them on top of figures rather than below. I've also come across academic journals that have taken this approach. Is there currently a way of doing this in pandoc? If not, could this feature be added?

Implementing a similar syntax to *tablenos*  would achieve this.

`Figure: Caption. {#fig:id}`

**Comment by tomduck** [comment]
Hi @jrlil.  I think this can be accomplished with a small addition to your latex template.  Try adding the following code somewhere before `\begin{document}`:

``` .latex
\usepackage{floatrow}
\floatsetup[figure]{capposition=top}
```

Here is my source for the idea: https://tex.stackexchange.com/questions/14859/placing-figure-captions-at-the-bottom

**Comment by lillemets** [comment]
If I'm not mistaken, this solution assumes that pandoc is used to convert _.md_  only to Latex (it's unclear to me why wouldn't anyone use Latex in the first place). For example, I need to create reports in _.docx_ to collaborate with my colleagues who only know how to use Microsoft Office. So it would be nice to have such functionality inside the pandoc filter.

**Comment by tomduck** [comment]
No, this isn't an assumption.  Pandoc's workflow goes like this:

```
INFILE -> pandoc reader -> JSON -> filters -> JSON -> pandoc writer -> OUTFILE
```

The reader reads whatever format, and the writer writes whatever format.  The writer uses a template in producing LaTeX/pdf output.  Any change that you make in the template will apply regardless of the input format.

Filters operate on the internal JSON file representation, before the writer stage.

If you want docx output, then it is the pandoc docx writer that applies.  There is no template to adjust, and so there is less control.  Any needs you have for docx output would need to be implemented in the docx writer.  There is nothing a filter can do about that.

Hopefully this helps clarify matters.

Cheers,
Tom

**Comment by tomduck** [comment]
Hi @jrlil.  In re-reading my reply, I think I may have mistook your meaning.  It is true that pandoc-fignos is only for processing markdown documents.  The output format is arbitrary.

A filter can do much to adjust output to LaTeX/pdf, and even more can be done by modifying pandoc's LaTeX template.  Unfortunately, there is little a filter can do to fine-tune docx output.  That is entirely the domain of pandoc's docx writer.

In any case, is there anything more that I can help you with in this Issue?

Cheers,
Tom

**Comment by lillemets** [comment]
Thank you for the explanation. I wan't sure I understood you correctly, but seems like I did.

The filters you created are extremely useful. But I think I could use something much simpler. A filter that only added a number and nothing else would actually be perfect for me. Something that I could use like this: `#series1:title1`. This would allow refering to everything I want  (e.g. section headings) and format references however I want. Maybe there'll be something like that one day.

I think this issue can be closed and thanks for creating these filters!

**Comment by tomduck** [comment]
Thanks, @jrlil.  I have been thinking about putting together a section numbers filter.  Stay tuned. :o)  Cheers, Tom.
