### ISSUE TITLE
Error running pandoc-fignos with new pandoc 1.18

### ISSUE THREAD

**Issue by kdheepak** [tomduck/pandoc-fignos#30]
Hi, 

I get the following error with Pandoc v1.18

```
Traceback (most recent call last):
  File "/Users/$USER/anaconda/envs/paper-env/bin/pandoc-fignos", line 11, in <module>
    sys.exit(main())
  File "/Users/$USER/anaconda/envs/paper-env/lib/python2.7/site-packages/pandoc_fignos.py", line 353, in main
    meta = doc[0]['unMeta']
KeyError: 0
pandoc: Error running filter pandoc-fignos
Filter returned error status 1
make: *** [ieeetex] Error 83
```

I believe the filter API has changed in the new version of Pandoc

**Comment by LATBauerdick** [comment]
Same problem here! Using pandoc 1.18 as distributed through home-brew.

Traceback (most recent call last):
   File "/usr/local/bin/pandoc-fignos", line 11, in <module>
     sys.exit(main())
   File "/usr/local/lib/python2.7/site-packages/pandoc_fignos.py", line 
353, in main
     meta = doc[0]['unMeta']
KeyError: 0
pandoc: Error running filter pandoc-fignos
Filter returned error status 1
make: **\* [output.pdf] Error 83

**Comment by tomduck** [comment]
Thank you for your feedback.  I have reproduced the error and am working on a fix.  It looks like pandoc has changed its JSON format.

**Comment by kdheepak** [comment]
Wow @tomduck thanks for the quick updates! This works!

**Comment by kdheepak** [comment]
And thanks for updating `pandoc-eqnos` and `pandoc-tablenos` while you were at it.

**Comment by tomduck** [comment]
Excellent news, @kdheepak!  Thanks for your feedback.  :o)

Cheers,
Tom
