### ISSUE TITLE
"Invalid expression" error with python 2.7.3

### ISSUE THREAD

**Issue by guillerodriguez** [tomduck/pandoc-fignos#32]
I am trying pandoc-fignos with pandoc-1.18 on Ubutu 12 and get the following error:

```
$ pandoc --filter pandoc-fignos demo.md
Traceback (most recent call last):
  File "/usr/local/bin/pandoc-fignos", line 9, in <module>
    load_entry_point('pandoc-fignos==0.18.1', 'console_scripts', 'pandoc-fignos')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/pandoc_fignos.py", line 50, in <module>
    import pandocxnos
  File "/usr/local/lib/python2.7/dist-packages/pandocxnos/__init__.py", line 1, in <module>
    from .core import *
  File "/usr/local/lib/python2.7/dist-packages/pandocxnos/core.py", line 419, in <module>
    _REF = re.compile(r'^((?:.*{)?[\*\+!]?)@([^:]*:[\w/-]+)(.*)?')
  File "/usr/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 242, in _compile
    raise error, v # invalid expression
sre_constants.error: nothing to repeat
pandoc: Error running filter pandoc-fignos
Filter returned error status 1
```

If I don't use pandoc-fignos, the same input file completes successfully:

```
$ pandoc demo.md
<p>Some data are shown in fig. <span class="citation">@fig:data</span>.</p>
<div class="figure">
<img src="plot1.png" alt="Some data." id="fig:data" />
<p class="caption">Some data.</p>
</div>
```

The input file is as simple as it gets:

```
$ cat demo.md

Some data are shown in fig. @fig:data.

![Some data.](plot1.png){#fig:data}


```

Any hint ?

**Comment by tomduck** [comment]
Thanks for your feedback, @guillerodriguez.  It looks like the old version of python (2.7.3) used by Ubuntu Precise can't process the regular expression I use to identify references.  I will install Precise into a virtual machine and see if I can find a fix.  Cheers, Tom.

**Comment by tomduck** [comment]
[This thread](https://stackoverflow.com/questions/15940985/python-can-not-compile-that-regex-sre-constants-error-nothing-to-repeat) on StackOverflow and [this Issue](https://bugs.python.org/issue214033) at bugs.python.org seem to explain the behaviour.

**Comment by tomduck** [comment]
Hi @guillerodriguez.  I think that I may have this problem solved.  Could you please check by installing the `nextrelease` branch of `pandoc-xnos`?  This is library code for `pandoc-fignos` and friends.  The usual way to do this (note the root prompt) is:

```
# pip install --upgrade git+https://github.com/tomduck/pandoc-xnos.git@nextrelease
```

Alternatively, download the `nextrelease` sources and do a manual install.

Then run your test that exposes the bug.  If the test still fails then I will take the virtual machine approach for further trials under python 2.7.3.

Thanks, Tom.

**Comment by guillerodriguez** [comment]
@tomduck Indeed, looks like the changes in `nextrelease` have fixed the problem. Good job :+1:

**Comment by tomduck** [comment]
**FANTASTIC.**  I just pushed out updated versions of pandoc-fignos and friends.  Thanks again for your help, @guillerodriguez.
