### ISSUE TITLE
Multiple figures on a single line are not referenced.

### ISSUE THREAD

**Issue by naught101** [tomduck/pandoc-fignos#36]
If there are two figures on one line (or one two lines, with no blank in between), then figure referencing does not work. e.g.:

```{markdown}
![some figure](path/to/image1.png}{#fig:one}
![another fig](path/to/image2.png}{#fig:two}
```

These figures will not be referenced. Not sure if this is intended behaviour, but if it is, maybe a note in the troubleshooting section? I just wasted a couple of hours trying to figure it out..

**Comment by tomduck** [comment]
Thanks for your feedback and sorry for the long delay.

This is actually intended behaviour.  According to the pandoc README, figures must occur by itself in a paragraph.  Pandoc-fignos is not responsible for this behaviour.
