### ISSUE TITLE
Installing in Mac

### ISSUE THREAD

**Issue by Hipomenes** [tomduck/pandoc-fignos#37]
Hi there, I have not been able to install pandoc-fignos in Mac. I tried the command you suggest (also installed Python 3 before), and just get this:

> sudo: pip: command not found

Thanks!

**Comment by iandol** [comment]
Try to use `pip3` which some python installs use:

``` 
pip3 install pandoc-fignos
```

I use miniconda to install python and there it is `pip`

**Comment by Hipomenes** [comment]
Of course. Thanks a lot! I was able to install it and use it within minutes. Works like a charm, thanks so much.

**Comment by tomduck** [comment]
Thanks for your feedback, @Hipomenes, and for your answer @iandol.  I will include a note on `pip3` in the installation instructions.
