### ISSUE TITLE
Issue with pandoc-fignos and -tablenos with LaTeX beamer class

### ISSUE THREAD

**Issue by bidspells** [tomduck/pandoc-fignos#38]
Hi, 

I'm using pandoc-fignos/-tablenos with the LaTeX beamer class. It seems that both filters create double tags for each caption such as 

    Tabelle 1: Table 1: Priority Inversion

The generated LaTeX code is 

    \caption{Table 1: Priority Inversion}\tabularnewline

The original markdown

  `Table: Priority Inversion {#tbl:ps2}`

Everything's works fine with Article or Report class, it's just Beamer causing trouble. 

Is this a bug?

Best,
Bid

**Comment by tomduck** [comment]
Sorry for the delay, @bidspells.  I can confirm that this is a bug, and am working on a fix.

**Comment by tomduck** [comment]
Hi Bid,

I have just added beamer support to all of the pandoc-xnos filters.  It looks like everything is working, including cleveref support.  Please re-open this Issue if problems persist.

Thank you for your feedback.

Cheers,
Tom
