### ISSUE TITLE
Does not work with pandoc version 2.0

### ISSUE THREAD

**Issue by dnebauer** [tomduck/pandoc-fignos#40]
I'm currently running pandoc from nightly builds, which means I am running pandoc 2.0:

```sh
$ pandoc --version
pandoc 2.0
Compiled with pandoc-types 1.17.0.5, texmath 0.9.4.1, skylighting 0.3.3
```

When I attempt to use pandoc-fignos I get a version-related error message:

```sh
$ echo 'test' | pandoc --filter pandoc-fignos -t html5
Traceback (most recent call last):
  File "/usr/local/bin/pandoc-fignos", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pandoc_fignos.py", line 379, in main
    PANDOCVERSION = pandocxnos.init(args.pandocversion, doc)
  File "/usr/local/lib/python2.7/dist-packages/pandocxnos/core.py", line 165, in init
    raise RuntimeError(msg)
RuntimeError: Cannot understand pandocversion=2.0
Error running filter pandoc-fignos:
Filter returned error status 1
```

The regular expression for valid pandoc versions in in line 153 of /usr/local/lib/python2.7/dist-packages/pandocxnos/core.py:

```python
pattern = re.compile(r'^1\.[0-9]+(?:\.[0-9]+)?(?:\.[0-9]+)?$')
```

This matches the current debian/testing version of pandoc, 1.19.2.1, which runs with pandoc-fignos without any problem.

If I alter line 153 to also match version 2.0:

```python
pattern = re.compile(r'^[1-2]\.[0-9]+(?:\.[0-9]+)?(?:\.[0-9]+)?$')
```

then pandoc version 2.0 runs just fine with the pandoc-fignos filter.

**Comment by tomduck** [comment]
Thanks for this report, @dnebauer.  I made the change as you suggested, and pushed out pandoc-xnos 0.10 to pypi.  Cheers!
