### ISSUE TITLE
cross reference number failed when italiced or bolded

### ISSUE THREAD

**Issue by shixuguo** [tomduck/pandoc-fignos#45]
it works when code is like below:
````
{@fig:1}

![Number one.](img/fig-1.png){#fig:1 =}
````

However,in some condition, I need set the number italic or bold, 
then the code failed,
the code is like below:

````
**{@fig:1}**

![Number one.](img/fig-1.png){#fig:1 =}
````

any solution?

**Comment by tomduck** [comment]
Thanks for this feedback, @shixuguo.  I agree this appears to be a problem and will look into it further.

**Comment by tomduck** [comment]
I have fixed the bug in the `nextrelease` branch of the `pandoc-xnos` library.  You can install it with the following command (as root):

    pip install --upgrade git+https://github.com/tomduck/pandoc-xnos.git@nextrelease

If it works for you then I will prepare a pypi release.

**Comment by shixuguo** [comment]
great！ it works now！  thanks！

**Comment by tomduck** [comment]
Excellent.  I pushed out pandoc-xnos 0.14. Future version of pandoc-fignos and friends will require it.  Thanks again for the feedback.
