### ISSUE TITLE
Feature Request: Custom Section Offset Numbering

### ISSUE THREAD

**Issue by oribotic** [tomduck/pandoc-fignos#47]
I'm writing my thesis in markdown, now using fignos, and its great, thanks so much!

I've made a small hack on the code - not really a git user, so sorry, I would have issued a pull request, I'll try to work that out next time.

What I have done is added xnos-number-offset: its basically a prefix or starting offset for the section numbering, it works great for writing chapters in separate documents. Say I want all chapter 6 figures to start with 6.X.X. Or I want all the figures in Appendix 1 to start with A1. 

```
---
fignos-cleveref: On
fignos-plus-name: Figure
fignos-caption-name: Figure
xnos-number-offset: 6
xnos-number-sections: On
...

```

in 
```
def process(meta)

. . . . .

global numberoffset

. . . . .

    if 'xnos-number-offset' in meta and meta['xnos-number-offset']['c']:
        tmp = get_meta(meta, 'xnos-number-offset')
        numberoffset = tmp

```
and in 

   ```
def process_figures 

. . . . .

global numberoffset

. . . . .

 # For html, hard-code in the section numbers as tags
    kvs = PandocAttributes(attrs, 'pandoc').kvs
    if numbersections and fmt in ['html', 'html5'] and not 'tag' in kvs:
        if numberoffset:
            cursec = numberoffset
        else:
            if kvs['secno'] != cursec:
                cursec = kvs['secno']
                Nreferences = 1
        kvs['tag'] = cursec + '.' + str(Nreferences)
        Nreferences += 1

```

I've only performed a quick hack, but the idea could be a useful addition if implemented properly

**Comment by tomduck** [comment]
Thank you for this contribution, and sorry for the delay.  I hope that the filter has been working well for you.  I'm going to leave this on my to-do list and have a closer look at it before September (when classes start again and time becomes short).

**Comment by tomduck** [comment]
At long last this is actually implemented.  It is in the 2.0 branch, which can be installed as a beta release (for now) using

    pip install pandoc-fignos --upgrade --pre --user

I expect to push out a production release soon.  Thanks for your suggestion.

Cheers,
Tom

**Comment by oribotic** [comment]
Thanks Tom, top job!
