### ISSUE TITLE
Image link attributes

### ISSUE THREAD

**Issue by bastionJersey** [tomduck/pandoc-fignos#48]
I hadn't used this for about a year, so I updated it (using pip on a Mac) after I updated pandoc. So now I have pandoc 2.1.3 and pandoc-fignos 1.2.0. I also run it with citeproc but I'm careful to have fignos first. It all worked a year or so ago, but now it doesn't seem to process anything. 

Here's my command line: 

`
pandoc /Users/adam/Dropbox/projects/papers2018/selfTracking/draft.md -o third_draft.pdf --filter pandoc-fignos --filter pandoc-citeproc --csl /Users/adam/Dropbox/pandocStuff/styles-master/apa.csl --include-in-header /Users/adam/Dropbox/pandocStuff/titlesec.tex --include-in-header /Users/adam/Dropbox/pandocStuff/figsfloat.tex --template /Users/adam/Dropbox/pandocStuff/mytemplate.tex --pdf-engine=xelatex --toc
`

And this is the markdown:

```
#### Stress over time

![Time all measures][image-1]{#fig:technicalprocess}

Figure {@fig:technicalprocess} shows
```

And here's how the pdf turns out:

![screen shot 2018-04-24 at 19 27 09](https://user-images.githubusercontent.com/6375545/39206529-92a2c6aa-47f5-11e8-99f4-6341ee7f64c2.png)

Citeproc tries to process it and complains there's no reference. 

I've tried uninstalling - it complains about fignos being missing then so I know it's being picked up by pandoc - and reinstalling. I've uninstalled and re-installed pandoc, too. I've run the command without citeproc and it doesn't do anything then, either. Is there something I can do to find out what's going on? I've tried it with files that definitely worked before I updated it!

**Comment by bastionJersey** [comment]
I have solved my own problem, kind of. In the markdown above you can see I was using reference links to the images. Tried it with just a straight filename: 

`![Time all measures.](/Users/adam/Dropbox/selfTracking/graphs/time_allMeasurements.png){#fig:technicalprocess}`

And it works perfectly. So, not sure if that's an issue or not. It worked with reference links before, I'm pretty sure of it. (I'm on MacOS 10.13.4, by the way.) But if it doesn't any more, that's fine too!

**Comment by tomduck** [comment]
Hi there.  Thanks for your feedback.

I think that your syntax is incorrect.  Notice that in the pdf you produced that the image attributes are not processed.  Pandoc normally does its own image attribute processing.  The fact it didn't in this case tells us that pandoc is not happy with what you wrote.

Here is an example of correct reference link syntax from the pandoc-fignos test suite:

~~~
![Number three. Reference to +@fig:1.][ref-link]

[ref-link]: img/fig-3.png {#fig:3 width=1in}
~~~

Notice that the attributes belong with the link.  I would agree that this is counter-intuitive, but it does appear to be consistent with the pandoc docs (see the section on [link_attributes](https://pandoc.org/MANUAL.html#extension-link_attributes)).

Cheers,
Tom

**Comment by bastionJersey** [comment]
Thanks; that’s solved a puzzle for me. It hadn’t occurred to me to check the Pandoc docs, because I didn’t realise fig-nos was set in an attribute of the image. I had just switched to inline links and it’s been working great! Such a useful utility. 

Thanks!

**Comment by tomduck** [comment]
I'm glad it worked out.  Cheers!
