### ISSUE TITLE
Feature Request: Subfigures

### ISSUE THREAD

**Issue by gepcel** [tomduck/pandoc-fignos#50]
By "subfigures", I mean multiple figures in the same line. And support caption for the whole figure and for subfigures, and references. Basically, it's what [pandoc-crossref](http://lierdakil.github.io/pandoc-crossref/#subfigures) does, but I prefer using pandoc-fignos.

Thanks.

**Comment by tomduck** [comment]
Thanks for your input, @gepcel.

To implement this feature I would need a well thought out spec to work from.  Does such a spec exist?
It has to have well-defined behaviours for at least pdf and html output.  One of the design goals for pandoc-fignos and friends is to equally well support both output formats (and others as possible).

I'm a bit worried that this is getting away from what pandoc-fignos does (cross-referencing).  Would it be better to have a separate filter for subfigures?

**Comment by gepcel** [comment]
I'll think of something and reply later.

**Comment by slochower** [comment]
Hi @tomduck, just curious if you've had any further thoughts on this. I, too, have been using `pandoc-crossref` for this, but it is not as ideal as `pandoc-fignos` for a number of reasons.

**Comment by tomduck** [comment]
Hi @slochower.  I'm just getting going on pandoc-fignos again after a long absence.  Let me update pandoc-fignos for the new pandoc releases and get back to you.  As noted in my earlier comment, I would need some help with a spec for the markdown and also in determining what the latex and html behaviours should be like.

**Comment by slochower** [comment]
> would need some help with a spec for the markdown

I'm certainly no expert, but the easiest, most fluid, and most natural syntax would be to treat two consecutive figures as two subfigures inside of a single figure. I'm sure there lots of issues to be uncovered with this, but that's where I'd start. 
```
![Caption 1](figure1.png){#fig:subfigure1}
![Caption 2](figure2.png){#fig:subfigure2}
```
Citations, like `+@fig:subfigure1` might render as fig. 1a. 

> determining what the latex

As a naive user, I would probably expect something similar to [`subfigure`](https://www.overleaf.com/learn/latex/How_to_Write_a_Thesis_in_LaTeX_(Part_3):_Figures,_Subfigures_and_Tables#Subfigures).

>  and html behaviours should be like.

I'm guessing it would be to put the subfigures into a `<div>` but I'm not sure.

**Comment by tomduck** [comment]
A few notes:

1) The TeX approach recommended above uses the [subcaption package](http://mirrors.concertpass.com/tex-archive/macros/latex/contrib/caption/subcaption.pdf), which is [recommended](https://tex.stackexchange.com/q/13625) over other options.

2) A stacked layout using subcaption is discussed [here](https://tex.stackexchange.com/questions/120700/vertical-spacing-using-subcaption-package).

3) Perhaps a markdown syntax like this would work:

   ~~~
   ::: {#fig:one}

   ![Caption 1a](figure1.png){#fig:one-a}

   ![Caption 1b](figure2.png){#fig:one-b}

   Caption 1.
   :::
   ~~~

   The above uses [pandoc divs](https://pandoc.org/MANUAL.html#divs-and-spans).  Note that figures must be on their own line according to pandoc.  Configuration items could be added to the main div and subfigure attributes.

4) The next step is to generate some latex and html code (these are essential target formats).  Docx is going to require input from someone who knows what they are doing with OOXML.

**Comment by timtroendle** [comment]
While this feature does not exist, is there a manual workaround? I can create a single figure with subfigures `a` and `b` for example. However, I don't find a way to avoid whitespace when referring to it:

With a figure tagged `#fig:one`, `+@fig:one a` renders to `fig. 1 a`. `+@fig:onea` does not render of course.

---
EDIT: The solution are curly braces. `{@fig:one}a` will render to `fig. 1a`.

**Comment by tomduck** [comment]
Thanks, @timtroendle.  I'm glad that you found the solution.  It hadn't occurred to me that the new facilities available in pandoc-fignos enabled references to hand-coded subfigures like this.  I will look into updating the pandoc-fignos documentation with your idea.

**Comment by tomduck** [comment]
I just wrote the workaround suggested by @timtroendle into the pandoc-fignos documentation.  Check it out: [demo4.md](https://raw.githubusercontent.com/tomduck/pandoc-fignos/master/demos/demo4.md) and [demo4.pdf](https://raw.githack.com/tomduck/pandoc-fignos/demos/demo4.pdf).  It is even possible to reference subfigures directly.

Some commentary:  It is challenging to provide syntax support for subfigures directly in pandoc-fignos because of the difficulty of making it flexible enough for LaTeX users while providing support in other output formats.  This indirect approach provides complete flexibility for LaTeX/pdf.  It may be possible to provide specialized indirect support for other output formats as well.  Users will have to let me know if that is needed.

**Comment by tomduck** [comment]
References to subfigure references are now supported for html/epub as well.  Subfigures for html/epub are implemented using pandoc's fenced divs.  Check it out: [demo5.md](https://raw.githubusercontent.com/tomduck/pandoc-fignos/master/demos/demo5.md) and [demo5.html](https://raw.githack.com/tomduck/pandoc-fignos/demos/demo5.html).

I think that this Issue can be closed.  If problems are found with subfigure references, please feel welcome to create a new Issue.

Cheers,
Tom
