### ISSUE TITLE
Feature request: reference figure number without creating a hyperlink

### ISSUE THREAD

**Issue by landlord11** [tomduck/pandoc-fignos#54]
It would be nice to have a syntax that places the figure number but does not create a hyperlink.  For example, maybe define a new prefix like `{^@fig::foo}`.  In my documents, when I add a caption to the figure, I'd prefer it not to pickup link formatting since the figure is immediately next to the caption so the link is unnecessary.  I don't have an opinion on an appropriate prefix, I just picked caret as an example.  Thank you!

**Comment by tomduck** [comment]
This feature is now implemented in the 2.0 branch.  A release through pypi will be made soon.  Thanks for your suggestion and sorry for the long delay.  --Tom
