### ISSUE TITLE
Figure numbering with Image Size attribute

### ISSUE THREAD

**Issue by shenghxie** [tomduck/pandoc-fignos#55]
It seems, for example `![](test.png){height=250px}{#fig:test}`, to be not working.
I am wondering what the correct syntax is?
Many thanks!

**Comment by shenghxie** [comment]
Ahh, researched for couple of hours, but figured it out myself right after I decided to post here.
It seems `![](test.png){height=250px #fig:test}` is the right way.

**Comment by tomduck** [comment]
I'm glad that it worked out.  :o)  Cheers, Tom
