### ISSUE TITLE
Issue with the execution of pandoc-fignos

### ISSUE THREAD

**Issue by vkeryvin** [tomduck/pandoc-fignos#56]
Dear Tom,

I'm getting this weird issue when compiling pandoc with pandoc filters pandoc-eqnos or pandoc-fignos or pandoc-tablenos.

Here is the dump

pandoc --standalone --filter pandoc-citeproc --filter pandoc-fignos --filter pandoc-tablenos --filter pandoc-eqnos --natbib --default-image-extension=eps --template=elsevier.latex --wrap=preserve -o Marchandise_2018.tex en-tete.yml Marchandise_2018.md Tables-Figures.md
Traceback (most recent call last):
  File "//anaconda/bin/pandoc-fignos", line 6, in <module>
    sys.exit(pandoc_fignos.main())
  File "//anaconda/lib/python3.5/site-packages/pandoc_fignos-0.20-py3.5.egg/pandoc_fignos.py", line 379, in main
  File "//anaconda/lib/python3.5/site-packages/pandoc_xnos-0.9-py3.5.egg/pandocxnos/core.py", line 165, in init
RuntimeError: Cannot understand pandocversion=2.2.3.2
Error running filter pandoc-fignos:
Filter returned error status 1
make: *** [Marchandise_2018.tex] Error 83

May you help me with this issue

Cheers

Vincent

**Comment by tomduck** [comment]
Dear Vincent,

Sorry for the long delay.

The problem is that you have a very old version of pandoc-fignos (v 0.20), even at the time you posted this message.  If you update to the current version there shouldn't be a problem.

Cheers,
Tom
