### ISSUE TITLE
References in "bracketed spans" are not resolved

### ISSUE THREAD

**Issue by slochower** [tomduck/pandoc-fignos#58]
Over at [pandoc-discuss](https://groups.google.com/d/msg/pandoc-discuss/2l8fVgPxAwk/BP4HGQzECQAJ) I have been trying to combine a pandoc Markdown "native span" and a figure reference. Briefly, I wanted to color some text -- containing a figure reference -- red in multiple output formats. If I put brackets around the reference, the text is red, but the reference is not resolved. There is a minimal example in that thread. Do you have any idea what is going on?

**Comment by tomduck** [comment]
I can reproduce and agree this is a problem.

**Comment by tomduck** [comment]
Note that fenced divs work correctly.  It is the bracketed spans that do not.

**Comment by tomduck** [comment]
Thanks for this issue report, which is appreciated.  References from bracketed spans are now working.  Please update to pandoc-fignos 1.4, and let me know if you have any trouble with it.

Cheers,
Tom

**Comment by tomduck** [comment]
I'm pretty confident this is fully solved, and so am going to close this Issue.  If you have any problems with it, please go ahead and re-open it.

**Comment by slochower** [comment]
Great, thanks. Sorry I didn't reply to your earlier messages, it's been busy here. I'm confident your updates will fix the issue, but if not, I'll report back! Thanks again.

**Comment by tomduck** [comment]
No worries at all.  I haven't had time for this in a while, and so I am doing my best to clear away the backlog of Issues.

Your Issue turned out to be really interesting.  I wasn't even aware of bracketed spans, and working on this resolved a few things about pandoc's citation handling that were a bit of a mystery to me.  :smile:
