### ISSUE TITLE
conda install conflict with statsmodels

### ISSUE THREAD

**Issue by jacob-vintercapital** [tomduck/pandoc-fignos#63]
he2@T430s:~$  conda install -c ericmjl pandoc-fignos 
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - pandoc-fignos
  - statsmodels
Use "conda info <package>" to see the dependencies for each package.

**Comment by tomduck** [comment]
Thanks, and sorry for the delay.

Can you please show me the dependencies for both packages using "conda info".  I'm not a conda user, and so am going to need some help identifying the conflict.

**Comment by tomduck** [comment]
I was able to install statsmodels on my vanilla python distribution using

     pip install statsmodels --user

(pandoc-fignos was already installed).

Looking at the [setup.py](https://github.com/statsmodels/statsmodels/blob/master/setup.py) for statsmodels shows it depends on numpy, scipy, pandas, and patsy.  Pandoc-fignos depends on none of these things.

So, I don't think there is a dependency clash with the current versions of these projects.  At least, not any more.

**Comment by tomduck** [comment]
Aha!  A [search for pandoc-fignos on the Anaconda cloud](https://anaconda.org/search?q=pandoc-fignos) shows that ericmjl is distributing an ancient version of pandoc-fignos.  The  KloostermanLab distribution is somewhat newer, but still out-of-date.

The install instructions for pandoc-fignos indicate that `pip` should be used.  At present my official releases are posted on PyPI, which is the repository that `pip` accesses by default.

Some tips on using pip in a conda environment may be found [here](https://www.anaconda.com/using-pip-in-a-conda-environment/).

**Comment by tomduck** [comment]
I put a warning in the footnotes for the [pandoc 2.0 beta release](https://github.com/tomduck/pandoc-fignos/tree/2.0).
