### ISSUE TITLE
math in figure caption

### ISSUE THREAD

**Issue by c3018911** [tomduck/pandoc-fignos#66]
When including math or symbols (e.g. $\alpha$) within a figure caption, this is not picked up in the output to .docx. Works fine for pdf.

**Comment by tomduck** [comment]
Thanks for your feedback.  I can't reproduce this problem.  My tests show $\alpha$ makes it through to the docx.  But maybe we are doing things slightly differently.

Please check to make sure your pandoc-fignos version is at least 1.3 (use `$pip show pandoc-fignos`) and try again.  If the problem persists, then I would appreciate a minimal working example that demonstrates it.

**Comment by tomduck** [comment]
I think that this is probably not a current problem.  Please re-open if I am wrong.  Thanks, Tom.
