### ISSUE TITLE
Not working with current pandoc 1.16 build

### ISSUE THREAD

**Issue by Wind4Greg** [tomduck/pandoc-fignos#7]
Thanks for the great functionality. I've been using this with pandoc 1.15.2, then just started using the current pandoc 1.16 build (build from source) and pandoc-fignos stopped working. I went to the 1.16 build since it has the new figure size specification capability. I'm wondering if this broke the filter, it uses a similar id syntax.
Cheers
Greg B.

**Comment by tomduck** [comment]
Thanks for the report.  I should have a fix within a day or two.  Cheers!

**Comment by Wind4Greg** [comment]
Thanks. But enjoy the holidays first!

**Comment by tomduck** [comment]
I pushed a new version to github.  Could you please install it from source and see if it works for you?  If everything is OK then I will post a new version to pypi.  Thanks for your help!

**Comment by Wind4Greg** [comment]
Downloaded, installed, and tested the update with Pandoc and a document containing three figures with numbering and references along with the new Pandoc figure size attribute. Worked great!
Next I need to start using your equation numbering filter. 
Thanks

**Comment by tomduck** [comment]
I just posted pandoc-fignos 0.5 to pypi.  Thanks again for your help.  Cheers!
