### ISSUE TITLE
tablenos format for figures

### ISSUE THREAD

**Issue by amichuda** [tomduck/pandoc-fignos#71]
Would it be possible to have fignos work with the same format as tablenos? i.e.

|-----------------|
| Figure here |
|-----------------|
Figure: My Caption {#fig:id}

The reason this would be cool is that I'm using [codebraid](https://github.com/gpoore/codebraid) to generate figures directly from code, so there isn't a hyperlink to some image file.

Thank you!

**Comment by tomduck** [comment]
Thanks for your question, @lordflaron.  The syntax for images and figures is defined by pandoc -- see [here](https://pandoc.org/MANUAL.html#images).  Pandoc-fignos is only responsible for figure and reference numbering.

There is an interesting discussion about introducing a new Figure element in [pandoc Issue #3177](https://github.com/jgm/pandoc/issues/3177).
