### ISSUE TITLE
odt writer produces 'Figure' label twice

### ISSUE THREAD

**Issue by lemzwerg** [tomduck/pandoc-fignos#72]
[pandoc 2.6]
[pandoc-fignos 1.4.2]

This simple input
```
See +@fig:1.

![test](https://weboverhauls.github.io/demos/svg/checkmark.svg){#fig:1}
```
if processed with
```
pandoc --write odt --filter pandoc-fignos --output bug.odt bug.md
```
produces the following output if viewed with LibreOffice 6.1.3.2 under GNU/Linux.

![bug](https://user-images.githubusercontent.com/1630245/62923259-a95dcf00-bdad-11e9-8d4a-43f94ae7e582.png)

**Comment by tomduck** [comment]
Thanks for this.  I just ran a test with the pandoc-fignos 2.0.0 beta, and it seems to be working as expected.  Could you give the beta a try?  It can be installed using

    pip install pandoc-fignos --upgrade --pre --user

I am hoping to release 2.0.0 soon, and some more feedback would be helpful.

**Comment by lemzwerg** [comment]
Using python 2.7.14, pandoc-fignos 2.0.0b3, and pandoc 2.6, I still get the same problem.  Since I see the problem with `odt2txt` too I'm quite sure that it is not a problem with my LibreOffice 6.2.5.2.

I've attached the ODT file.

[bug.odt.zip](https://github.com/tomduck/pandoc-fignos/files/3542235/bug.odt.zip)

**Comment by tomduck** [comment]
I can now reproduce the problem using pandoc versions 2.4-2.6.  The change in the odt writer for those versions was [rolled back](https://github.com/jgm/pandoc/issues/5474) for pandoc 2.7.3.  Hopefully upgrading is an option for you.

**Comment by lemzwerg** [comment]
OK, thanks for the hint.  I won't do an upgrade right now, but it's good to know that the problem won't appear with a recent pandoc version.

**Comment by tomduck** [comment]
I'm glad it worked out. :o)  Cheers, Tom.
