### ISSUE TITLE
Undefined environment if all figures do not have id

### ISSUE THREAD

**Issue by AlexandreRio** [tomduck/pandoc-fignos#73]
I'm running `pandoc-fignos 2.0.0b3` targeting latex.

I first tried pandoc-fignos on one figure of document and I had the following latex error:

    ! LaTeX Error: Environment fignos:no-prefix-figure-caption undefined.

I fixed it by adding ids to all my figures but I think it's an issue worth fixing.

Minimal document to produce this bug should be:

```markdown
![img1(img1)
![img2](img2){#img2}
```
    pandoc -t latex --filter pandoc-fignos doc.md

This will output `\begin{fignos:no-prefix-figure-caption}` with no previous declaration.

**Comment by tomduck** [comment]
Thanks for your feedback.  The problem, I think, is that you need to use the `--standalone` flag with pandoc to produce a TeX file that will compile.

**Comment by AlexandreRio** [comment]
Oh right, I compile multiple files to merge them, hence why I don't use `--standalone` at this point. Thanks for your quick answer.
