### ISSUE TITLE
[Question] Generating list of figures?

### ISSUE THREAD

**Issue by dendrondal** [tomduck/pandoc-fignos#74]
This same logic also applies to pandoc-tablenos. I'm wanting to generate a master list of all figures and numbers from a series of .md documents in one of said md documents. Is there a way to do this? Invoking ```\listoffigures``` prints nothing.

**Comment by tomduck** [comment]
Thanks for your question, @dendrondal.  Can you please provide me with a minimal working example of what you are trying to do?  I inserted `\listoffigures` into one of the demos provided with pandoc-fignos, and used pandoc to generate a pdf.  It provided the list of figures, as expected.

Cheers,
Tom

**Comment by tomduck** [comment]
I assume that this is no longer of interest.  If the problems persist, then please re-open.
