### ISSUE TITLE
Non-breaking space for clever refs in html 

### ISSUE THREAD

**Issue by timtroendle** [tomduck/pandoc-fignos#78]
Currently, clever refs create html like this:

```html
See fig. <a href="#fig:1">1</a>.
```

Which allows for line breaks between "fig." and its number. Would it be possible to (optionally?) add a non-breaking space in between, to prevent this from happening?

```html
See fig.&nbsp;<a href="#fig:1">1</a>.
```

This would be a great feature for the entire xnos suite imo.

**Comment by tomduck** [comment]
Good idea, and thanks for the patch.  This is now in the `nextrelease` branch.

**Comment by tomduck** [comment]
pandoc-fignos 2.3.0 is now released.  --Tom

**Comment by timtroendle** [comment]
Thanks and thanks for letting me know!

**Comment by timtroendle** [comment]
@tomduck This feature does not work in pandoc-fignos 2.3.0 and pandoc-xnos 2.4.2. It was working in https://github.com/tomduck/pandoc-xnos/pull/12, but there is a regression in https://github.com/tomduck/pandoc-xnos/commit/078e3fa879e8692d6b6f741e9dc28e984d27f0bb. In the commit, the non-breaking whitespace has been replaced by a normal (i.e. breaking) whitespace.

**Comment by tomduck** [comment]
OK, let's continue this at https://github.com/tomduck/pandoc-xnos/issues/14.  [Edit: Corrected link]
