### ISSUE TITLE
Failure running latest pandoc-fignos 2.3.0 with pandoc 2.10.1

### ISSUE THREAD

**Issue by finiteabelian** [tomduck/pandoc-fignos#82]
This worked with previous versions:

pandoc --filter pandoc-fignos --filter pandoc-eqnos -s -M "date=`date +'%d %B %Y'`" --bibliography doc/Citations.yaml -o README.pdf README.md doc/Manual.yaml
Traceback (most recent call last):
  File "/usr/local/bin/pandoc-fignos", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandoc_fignos.py", line 646, in main
    altered = functools.reduce(lambda x, action: walk(x, action, fmt, meta),
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandoc_fignos.py", line 646, in <lambda>
    altered = functools.reduce(lambda x, action: walk(x, action, fmt, meta),
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandocfilters.py", line 110, in walk
    res = action(item['t'],
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandocxnos/core.py", line 870, in process_refs
    _process_refs(value[-5]['c'][1][0]['c'], pattern, labels)
IndexError: list index out of range
Error running filter pandoc-fignos:
Filter returned error status 1
make: *** [README.pdf] Error 83

$ ls /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages
README.txt				pandoc_fignos-2.3.0.dist-info		pandocxnos				psutil-5.7.2-py3.8.egg-info
__pycache__				pandoc_fignos.py			pip					setuptools
easy_install.py				pandoc_xnos-2.4.1.dist-info		pip-20.2.dist-info			setuptools-47.1.0.dist-info
pandoc_eqnos-2.2.0.dist-info		pandocfilters-1.4.2-py3.8.egg-info	pkg_resources
pandoc_eqnos.py				pandocfilters.py			psutil

- Also, tried to revert pandoc from 2.10.1 to 2.10 but still had the same error.  Reverting to pandoc 2.9.2.1 worked.
- Python version is 3.8.5

**Comment by tomduck** [comment]
Thank you for this report.  It would appear that the problem occurs for uncaptioned tables with the new Table structure of pandoc 2.10.  I am working on a fix.

Cheers,
Tom

**Comment by tomduck** [comment]
The Issue has been fixed, and new versions of each filter (and the core) have been released.  If you find there is still a problem, please don't hesitate to re-open this issue.  Thanks for testing the new release and reporting the Issue so quickly.

Cheers,
Tom

**Comment by finiteabelian** [comment]
Tested with pandoc 2.10.1 and it now works.  Thanks so much for the quick response.
