### ISSUE TITLE
TypeError in pandocxnos.core.process_refs with Pandoc 2.11

### ISSUE THREAD

**Issue by dhimmel** [tomduck/pandoc-fignos#85]
Just encountered the following error with pandoc-2.11.0.4 ([CI log](https://github.com/manubot/rootstock/pull/386/checks?check_run_id=1377613538#step:7:41)):

```python-traceback
[INFO] Running filter pandoc-fignos
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/manubot/bin/pandoc-fignos", line 8, in <module>
    sys.exit(main())
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/pandoc_fignos.py", line 649, in main
    altered)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/pandoc_fignos.py", line 646, in <lambda>
    altered = functools.reduce(lambda x, action: walk(x, action, fmt, meta),
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/pandocfilters.py", line 111, in walk
    item['c'] if 'c' in item else None, format, meta)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/pandocxnos/core.py", line 873, in process_refs
    if value[-5]['c'][1]:
TypeError: list indices must be integers or slices, not str
```

**Comment by dhimmel** [comment]
From https://github.com/sergiocorreia/panflute/issues/142#issuecomment-723369393

> pandoc 2.11 uses pandoc-types 1.22

pandoc-types changelog for 1.22 at https://github.com/jgm/pandoc-types/blob/5950eebaba6c171d2d8b622c23244b73d87fc402/changelog#L1-L44.

**Comment by tomduck** [comment]
Thanks, @dhimmel.  I have updated to the latest pandoc version.  Please re-open this issue if you have any further trouble with it.

Cheers,
Tom

**Comment by dhimmel** [comment]
Thanks @tomduck that was quick. So I think I need to upgrade pandoc-xnos to [2.5.0](https://pypi.org/project/pandoc-xnos/2.5.0/) and that will fix things.

Linking to some of the commits related to this issue for my reference:

- https://github.com/tomduck/pandoc-fignos/commit/6ab8ac6e2d5ab89805e96a36fd01ba19e8f697a6
- https://github.com/tomduck/pandoc-fignos/commit/9dd614834fdd7e92b6d6c9d8265b9b462b65a180
- https://github.com/tomduck/pandoc-xnos/commit/32966df0da926103f4b6cfedc45d5bd688368b0b
- https://github.com/tomduck/pandoc-xnos/commit/dff6978fe1283cda1950ac6d494257e35b8d30de

**Comment by tomduck** [comment]
@dhimmel, you would definitely need to upgrade pandoc-tablenos as well if you are using that.  Cheers, Tom.
