### ISSUE TITLE
Pandoc HTML5 Video, Media Fragments

### ISSUE THREAD

**Issue by lamyergeier** [tomduck/pandoc-fignos#86]
Pandoc supports mp4 video using figure syntax, the following works as expected in html output

```markdown
![Media: Party Recordingg](./Party.mp4){#fig: width="500px"}
```

---

# Request

- Is it also possible to support additional media fragments like `#t` to play the video from certain start to certain stop time as given here [10 Advanced Features In The HTML5 <video> Player](https://blog.addpipe.com/10-advanced-features-in-html5-video-player/)

- For example, following is expected to play the video from 3045s to 3051s

```markdown
![Media: Party Recordingg](./Party.mp4){#fig: width="500px" #t=3045,3051}
```

**Comment by tomduck** [comment]
Hi @anishmittal2020.  Thanks for your interest in pandoc-fignos.  The purpose of this filter is to insert figure numbers and references.  It isn't meant to do much beyond that.  In principle, additional filters could be written to process other attributes.

From looking at the Web page you gave, however, I think you want something else entirely.  It looks to me like `#t=3045,3051` should be part of the source url.  i.e., something like
```
![Media: Party Recording](./Party.mp4#t=3045,3051){#fig: width="500px"}
```
I am not sure if pandoc supports this.  I have not tested it.

Cheers,
Tom

**Comment by lamyergeier** [comment]
Thanks Tom!

What you suggested is supported  by Pandoc! :)

**Comment by tomduck** [comment]
Wonderful!  I am glad it worked.  ☺︎  Cheers, Tom.
