### ISSUE TITLE
Label and sizing

### ISSUE THREAD

**Issue by SG-phimeca** [tomduck/pandoc-fignos#90]
Is it possible to combine the labeling syntax

    ![This is a caption.](figure/image.png){#fig:mylabel}

with the resizing syntax

    ![This is a caption.](figure/image.png){height=10%}

?

I tried variation around

    ![This is a caption.](figure/image.png){height=10%, #fig:mylabel}

which at best compile without appropriate labeling.

**Comment by maawoo** [comment]
Hi @SG-phimeca !
You might have _figured_ it out by now, but you can just combine attributes with a space. So for your example:
`![This is a caption.](figure/image.png){#fig:mylabel height=10%}`
If you run into any problems with that, something else is probably wrong.

**Comment by SG-phimeca** [comment]
Dear @maawoo ,
Thank you: I did not figured it out. Tried , ; and so on but not .

**Comment by daviddoji** [comment]
@SG-phimeca what works for me is the following syntax:
```![This is a caption.](figure/image.png){#fig:mylabel .class width=10%}```
